### PR TITLE
SCB-1351 Some issues about using toolkit plugin

### PR DESCRIPTION
**Pull request by MabinGo**
Signed-off-by: MabinGo <bin.ma@huawei.com>

### CODE REVIEW

**Comment by WillemJiang** [comment]
Please add some description about the issue, it's hard for us the trace the issue without detail information.

**Comment by MabinGo** [comment]
I have written down the issues in Apache ServiceComb JIRA SCB-1351.
commit 600796,fix the issue of invalid naming of generated contract files
commit fee7d12 and e306c9e,fix the issue of generating document failure
commit 2da7807,fix the issue of verifying contract file is not correct
commit 7e8c5bd,fix the issue of UT failure
commit 2cfa6f4,optimize toolkit user experience

**Comment by WillemJiang** [comment]
I think we need to create a JIRA for each issue fixing from you description.  It could help us generate a meaningful release note.

**Comment by MabinGo** [comment]
I have created JIRA(SCB-1358,SCB-1359,SCB-1360,SCB-1361) for each issues, and make SCB-1351 link to them.

**Comment by WillemJiang** [comment]
There are three .class in the PR, we are not supposed to put binary file into source repository.  If you want to do some Unit test on these compiled files, you can load the compiled file from target directory.

**Comment by MabinGo** [comment]
OK,the .class was removed,pls help to check again

**Pull request merged**
