### PR TITLE
[SCB-1621] use case with Apache ServiceComb Syncer

### PR DESCRIPTION
**Pull request by kakulisen**
This is a use case with Apache ServiceComb Syncer.
What is Syncer?
Syncer is a multiple servicecenters synchronization tool designed for large microservice architectures, supporting Heterogeneous servicecenters

### CODE REVIEW

**Comment by chanjarster** [comment]
Nice work! But I think it's more about Syncer not toolkit. @WillemJiang @MabinGo Any suggestions?

**Comment by WillemJiang** [comment]
Normally we just use the toolkit to generate the project skeleton for daily job. I don't think this a common user scenario we need to support in the toolkit.
@kakulisen Can you explain why did you create this PR?

**Comment by kakulisen** [comment]
Because the toolkit is used in this case, I simply thought it could be put here. After your reminder, I also find it inappropriate to put it here

Maybe I can put it in servicecomb-samples? Can you give me some advice? Thanks

**Comment by kakulisen** [comment]
I will close this PR, and follow-up questions about this case will be moved to the mailing list to discuss

**Pull request closed without merging**
