### PR TITLE
[SCB-1619] translate  comments of oas-generator

### PR DESCRIPTION
**Pull request by kakulisen**
translate  comments of oas-generator

### CODE REVIEW

**Comment by chanjarster** [comment]
LGTM

**Comment by kakulisen** [comment]
I did not add the logic code. But the test coverage is reduced by 0.0002%.
Do I need to add some additional test cases?

**Comment by WillemJiang** [comment]
@kakulisen You can ignore it.

**Comment by kakulisen** [comment]
ok

**Pull request merged**
